GOOGLE_API_KEY="AIzaSyA8VRL7WFe3GhVR_Uyexa5O0MG3h6FAMoc"
GROQ_API_KEY="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"
OPENWEATHERMAP_API_KEY="9aa169b87ce03f4b87b292b52f608f16"
QDRANT_URL="https://2f4f579f-dbef-4c3b-a08c-e1b861cbeebf.us-east4-0.gcp.cloud.qdrant.io"
QDRANT_API_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.xIOF3xexlJLsB7CX4lfq8qp-zB6sy0Q28ChEP11ArAk"
